FROM python
EXPOSE 5000
WORKDIR /usr/TPWebServices
COPY ./reportes ./reportes
RUN pip install pandas
RUN pip install flask
RUN pip install flask_cors
RUN pip install borb
CMD ["python", "reportes/app.py"]

