version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    restart: always
    container_name: front
    ports:
      - "5500:80"

  reportes:
    build:
      context: .
      dockerfile: Dockerfile.reportes
    restart: always
    container_name: reportes
    ports:
      - "5000:5000"

  administrador:
    build:
      context: .
      dockerfile: Dockerfile.admin
    restart: always
    container_name: admin
    ports:
      - "8081:8081"

  docente:
    build:
      context: .
      dockerfile: Dockerfile.docente
    restart: always
    container_name: docente
    ports:
      - "8083:8083"

  estudiante:
    build:
      context: .
      dockerfile: Dockerfile.estudiante
    restart: always
    container_name: estudiante
    ports:
      - "8082:8082"
