version: "3.8"

services:
  front:
    image: tp/front
    restart: always
    ports:
      - "5500:80"

  reportes:
    image: tp/reportes
    restart: always
    ports:
      - "5000:5000"

  administrador:
    image: tp/admin
    restart: always
    ports:
      - "8081:8081"

  profesor:
    image: tp/docente
    restart: always
    ports:
      - "8083:8083"

  estudiante:
    image: tp/estudiante
    restart: always
    ports:
      - "8082:8082"

  database:
    image: mysql:5.7
    ports:
      - "33061:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
