-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 19:14:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`inscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`inscripciones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fin` DATE NULL DEFAULT NULL,
  `inicio` DATE NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`materias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NULL DEFAULT NULL,
  `año_cuatrimestre` INT NULL DEFAULT NULL,
  `año_materia` INT NULL DEFAULT NULL,
  `carrera` VARCHAR(250) NULL DEFAULT NULL,
  `cuatrimestre` VARCHAR(250) NULL DEFAULT NULL,
  `dia` VARCHAR(250) NULL DEFAULT NULL,
  `hora_finalizacion` VARCHAR(250) NULL DEFAULT NULL,
  `hora_inicio` VARCHAR(250) NULL DEFAULT NULL,
  `nombre` VARCHAR(250) NULL DEFAULT NULL,
  `turno` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db`.`mesa_examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`mesa_examen` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NULL DEFAULT NULL,
  `dia` DATE NULL DEFAULT NULL,
  `hora` VARCHAR(255) NULL DEFAULT NULL,
  `materia_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK46gj66tpjtqbe97vuwlfpoe81` (`materia_id` ASC) VISIBLE,
  CONSTRAINT `FK46gj66tpjtqbe97vuwlfpoe81`
    FOREIGN KEY (`materia_id`)
    REFERENCES `db`.`materias` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NULL DEFAULT NULL,
  `apellido` VARCHAR(250) NULL DEFAULT NULL,
  `carrera` VARCHAR(250) NULL DEFAULT NULL,
  `contraseña` VARCHAR(250) NULL DEFAULT NULL,
  `dni` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `nombre` VARCHAR(250) NULL DEFAULT NULL,
  `nombre_usuario` VARCHAR(250) NULL DEFAULT NULL,
  `primer_login` BIT(1) NULL DEFAULT NULL,
  `rol` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db`.`notas_finales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`notas_finales` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `aprobado` BIT(1) NULL DEFAULT NULL,
  `inscripto` BIT(1) NULL DEFAULT NULL,
  `nota_examen` DOUBLE NULL DEFAULT NULL,
  `nota_final` DOUBLE NULL DEFAULT NULL,
  `usuario_id` BIGINT NULL DEFAULT NULL,
  `mesa_examen_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKb9wjsoitnu67ws3chrqwhdm0f` (`usuario_id` ASC) VISIBLE,
  INDEX `FKkefck5frmeqxv058wdi5wtr0c` (`mesa_examen_id` ASC) VISIBLE,
  CONSTRAINT `FKb9wjsoitnu67ws3chrqwhdm0f`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db`.`usuarios` (`id`),
  CONSTRAINT `FKkefck5frmeqxv058wdi5wtr0c`
    FOREIGN KEY (`mesa_examen_id`)
    REFERENCES `db`.`mesa_examen` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db`.`usuarios_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuarios_materia` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `inscripto` BIT(1) NULL DEFAULT NULL,
  `nota_cursada` DOUBLE NULL DEFAULT NULL,
  `nota_parcial_1` DOUBLE NULL DEFAULT NULL,
  `nota_parcial_2` DOUBLE NULL DEFAULT NULL,
  `materia_id` BIGINT NULL DEFAULT NULL,
  `usuario_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK431p9bsftcyj4ydritj7tjs9b` (`materia_id` ASC) VISIBLE,
  INDEX `FK68b1d3q6d2xqm21tbbv6sbxi0` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `FK431p9bsftcyj4ydritj7tjs9b`
    FOREIGN KEY (`materia_id`)
    REFERENCES `db`.`materias` (`id`),
  CONSTRAINT `FK68b1d3q6d2xqm21tbbv6sbxi0`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
