package com.unla.administrador.utilidades.enums;

public enum Materia {

    MATEMATICA,
    PROGRAMACION,
    ALGORITMOS,
    ARQUITECTURA,
    BASE_DE_DATOS,
    OBJETOS,
    INGENIERIA,
    SISTEMAS_OPERATIVOS,
    PROYECTO,
    REDES,
    ORGANIZACIONES,
    FUNDAMENTOS,
    PRUEBAS_DE_SOFTWARE,
    SISTEMAS_DISTRIBUIDOS,

}
